# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
 # Add and configure other services you need, here CouchDB
  services.couchdb = {
       enable = true;
       adminUser = "FIXME";
       adminPass = "FIXME";
  };
}




 
